name: 'Issues to Json'
description: 'Generate JSON from GitHub issues'
author: 'xaoxuu'

inputs:
  data_path:
    description: '数据文件存储路径'
    required: false
    default: '/v2/data.json'
  data_version:
    description: '数据结构版本号'
    required: false
    default: 'v2'
  sort:
    description: 'Issue排序方式和方向 (例如: created-desc, updated-asc, version-desc)'
    required: false
    default: 'created-desc'
  exclude_labels:
    description: '需要排除的Issue标签 (逗号分隔)'
    required: false
    default: '审核中, 无法访问'


runs:
  using: 'node20'
  main: 'dist/index.js'